# Generated by Django 4.2.21 on 2025-06-03 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
                ('size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='filemanager_name_ee8e7e_idx'), models.Index(fields=['content_type'], name='filemanager_content_0251fe_idx'), models.Index(fields=['created_at'], name='filemanager_created_c7bea8_idx')],
            },
        ),
    ]
