# Generated by Django 4.2.21 on 2025-06-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_hash',
            field=models.CharField(db_index=True, default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='original_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='filemanager.file'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['content_hash'], name='filemanager_content_a2d194_idx'),
        ),
    ]
