# Generated by Django 4.2.21 on 2025-06-03 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model

def create_default_superuser(apps, schema_editor):
    User = get_user_model()
    # Create a default superuser if none exists
    if not User.objects.filter(is_superuser=True).exists():
        User.objects.create_superuser(
            'admin',
            'admin@example.com',
            'admin123'
        )
    # Get the first superuser
    superuser = User.objects.filter(is_superuser=True).first()
    
    # Update all existing files to belong to the superuser
    File = apps.get_model('filemanager', 'File')
    File.objects.filter(owner__isnull=True).update(owner=superuser)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0002_file_content_hash_file_is_original_and_more'),
    ]

    operations = [
        # First add the owner field as nullable
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Run the function to create superuser and update existing files
        migrations.RunPython(create_default_superuser),
        # Make the owner field required
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ] 