# Generated by Django 4.2.21 on 2025-06-03 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model

def assign_files_to_user(apps, schema_editor):
    User = get_user_model()
    # Get the first available user (admin)
    user = User.objects.filter(username='admin').first()
    
    if user:
        # Update all existing files to belong to the admin user
        File = apps.get_model('filemanager', 'File')
        File.objects.filter(owner__isnull=True).update(owner=user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0002_file_content_hash_file_is_original_and_more'),
    ]

    operations = [
        # First add the owner field as nullable
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Run the function to assign existing files to admin user
        migrations.RunPython(assign_files_to_user),
        # Make the owner field required
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ] 