# Generated by Django 4.2.21 on 2025-06-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_file_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
    ]
